[package]
name = "pycode"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "pycode"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.0"
spike_rs = { path = "./spike-rs"}

[build-dependencies]
cmake = "*"
bindgen = "*"
